- hosts: all
  tasks:
  - name: "Copying jdk"
    copy:
            dest: "/opt/jdk-8u171-linux-x64.rpm"
            src: "software/jdk-8u171-linux-x64.rpm"
  - name: "Install jdk"
    shell: "rpm -i /opt/jdk-8u171-linux-x64.rpm"
    ignore_errors: yes
  - name: "Copying Hadoop"
    copy:
            dest: "/opt/hadoop-1.2.1-1.x86_64.rpm"
            src: "software/hadoop-1.2.1-1.x86_64.rpm"
  - name: "Install Hadoop"
    command: "rpm -i /opt/hadoop-1.2.1-1.x86_64.rpm --force"
    ignore_errors: yes
